- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/Appointment.java
- src/main/java/seedu/address/model/person/BloodType.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/model/person/AppointmentTest.java
- src/test/java/seedu/address/model/person/BloodTypeTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
added blood type fully and an empty appointment class
Closes #49
> add blood type field to person contact

- src/main/java/seedu/address/logic/commands/AssignCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/AssignCommandParser.java
Add and implement AssignCommand.java and AssignCommandParser.java
Update AddressBookParser.java
Closes #52
> Add "assign" feature

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Pull request for implementing the edit feature 
closes #48
> Branch edit feature

- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/ListCommandParser.java
- src/main/java/seedu/address/model/person/PersonHasAppointmentPredicate.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/ListCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
- src/test/java/seedu/address/model/person/PersonHasAppointmentPredicateTest.java
Pull request to upgrade list feature
Closes #56
> Upgrade list feature to include appointment

- src/main/java/seedu/address/logic/commands/AssignCommand.java
- src/test/java/seedu/address/logic/commands/AssignCommandTest.java
- src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
Modified so that number of nurses that can be assigned to a patient is limited to 2.
Added test cases.
Closes #59, #70
> Improve "assign" feature

- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
> Fix AddressBookParserTest.java file

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
> Fix Edit Command bugs

- appmap.yml
- src/main/java/seedu/address/logic/commands/AssignCommand.java
- src/main/java/seedu/address/logic/commands/FindNurseCommand.java
- src/main/java/seedu/address/logic/commands/FindPatientCommand.java
- src/main/java/seedu/address/logic/commands/ScheduleCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
- src/main/java/seedu/address/model/checkup/Checkup.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/storage/JsonAdaptedCheckup.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/PersonListCard.fxml
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Testing to see if branch_SimpleScheduleCheckup works
> Branch simple schedule checkup

- build.gradle
- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/AssignCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/BloodType.java
- src/main/java/seedu/address/model/person/MedicalHistory.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/tag/Tag.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedMedicalHistory.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- Improved the edit function and add function to allow the editing of medical history and adding the optional medical history for a patient.
- Added some more fixes to the User Interface (UI)
close #81 
close #86
> Improve Edit and Add functions

- docs/UserGuide.md
> edit quick start of user guide

- docs/UserGuide.md
Added table of contents
added list checkups description
> Branch edit user guide

- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/logic/commands/ScheduleCommand.java
- src/main/java/seedu/address/logic/parser/ListCommandParser.java
- src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/PersonHasCheckupPredicate.java
add list checkup function
edited ListCommand and ListCommandParser to allow handling of list checkups
Removed capitalise in ListCommandParser as appointment allows capitalization handling already
> Branch test schedule

- build.gradle
- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/AssignCommandParser.java
- src/main/java/seedu/address/logic/parser/ViewCommandParser.java
- src/test/java/seedu/address/logic/commands/CommandResultTest.java
Implement the "view" feature:
- the view command will display the nurse or patient at the specified index
- for patients: displays medical history if any
Closes #82
> Implement "view" feature

- build.gradle
- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/AssignCommandParser.java
- src/main/java/seedu/address/logic/parser/ViewCommandParser.java
- src/test/java/seedu/address/logic/commands/CommandResultTest.java
- src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Added a test case for the "view" feature.
> Add test case for "view" feature

- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/Name.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
Added sorting by earliest checkup while normal list is sorted by alphabetical order
Stored all names in full capital letter for better sorting
closes #92
> fix list check up function

- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/logic/commands/ScheduleCommand.java
- src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/Name.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
> Branch edit checkup

- src/main/java/seedu/address/logic/commands/FindPatientCommand.java
- src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/test/java/seedu/address/logic/commands/FindNurseCommandTest.java
- src/test/java/seedu/address/logic/commands/FindPatientCommandTest.java
- src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
- src/test/java/seedu/address/model/checkup/CheckupTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Include the relevant test cases for scheduling checkup
close #85
> Branch simple schedule checkup test

- src/test/java/seedu/address/logic/commands/ViewCommandTest.java
- src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Added comprehensive test cases for ViewCommand.java and ViewCommandParser.java
Closes #118
> Add more test cases for the "view" feature

- src/test/java/seedu/address/logic/commands/AssignCommandTest.java
Fixed test cases for AssignCommandTest.java
> Fix test cases

- src/main/java/seedu/address/model/person/NextOfKin.java
> Fix NOK acceptable input bugs

- src/main/java/seedu/address/logic/commands/AssignCommand.java
- src/main/java/seedu/address/logic/commands/AssignDeleteCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/AssignCommandParser.java
- src/main/java/seedu/address/logic/parser/AssignDeleteCommandParser.java
- src/test/java/seedu/address/logic/commands/AssignCommandTest.java
- src/test/java/seedu/address/logic/commands/AssignDeleteCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
- src/test/java/seedu/address/logic/parser/AssignDeleteCommandParserTest.java
Implement the assign delete command so that assigned nurses can be removed from patients with this command, instead of using the existing tag clearing method.
Closes #186 
Closes #188 
Closes #170
> Implement "assign delete" feature

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/model/person/Name.java
- src/test/java/seedu/address/model/person/NameTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
fix name alphabetical, repeated whitespaces
fix test cases
closes #200 
closes #175 
closes #174 
closes #173
> fix add command sample format

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/model/person/Email.java
- src/main/java/seedu/address/model/person/Phone.java
- src/test/java/seedu/address/model/person/EmailTest.java
- src/test/java/seedu/address/model/person/PhoneTest.java
Fixes made:
- Allow phone number to have spacing (min 3 digits per group) and checks if its all zeros, which will give error message if all is zero for phone number
- Greater checks for email and implements compulsory .com after domain name
fixes #150
> Fix more bugs from alpha test

- docs/UserGuide.md
Updated the user guide with the most recent changes.
Closes #183
> Update the user guide

- src/main/java/seedu/address/model/person/MedicalHistory.java
- src/test/java/seedu/address/model/person/MedicalHistoryTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/model/person/PhoneTest.java
- src/test/java/seedu/address/model/tag/TagTest.java
Added test cases to:
- MedicalHistoryTest.java
- PersonTest.java
- PhoneTest.java
- TagTest.java
> Add more test cases for code coverage

- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/model/person/PersonHasSameNamePredicate.java
> Edit view command to retain UI after other commands

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/model/person/MedicalHistory.java
Fixed bugs with Edit feature to relation with features such as:
- view command
- find command
Also enabled medical history to accept commas.
> Fixed a few bugs with Edit feature

- src/main/java/seedu/address/logic/commands/FindNurseCommand.java
- src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
- Refactor code to adhere to checkstyle
> Branch code quality

- README.md
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/Email.java
- src/main/java/seedu/address/model/person/MedicalHistory.java
- src/main/java/seedu/address/model/person/Phone.java
- src/test/java/seedu/address/model/person/EmailTest.java
Adds a feature to limit the phone number length allowable to not more than 17 digits (excluding spaces)
Fixes #318 
Fixes #300 
Fixes #283 
Fixes #282 
Fixes #268
> Limit phone number length

- src/main/java/seedu/address/logic/commands/AssignCommand.java
- src/test/java/seedu/address/logic/commands/AssignCommandTest.java
Make error messages for invalid index values specific to the user input.
Closes #279 
Closes #284
> Update error messages for assign command

- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/person/NextOfKin.java
Special characters apostrophe, slash and hypens are now accepted in names
closes #265
> Allow special character in name

- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/AssignDeleteCommandTest.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/commands/FindNurseCommandTest.java
- src/test/java/seedu/address/logic/commands/FindPatientCommandTest.java
- src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
- src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Fix test cases due to mesaage change
> fix test case

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/address/model/checkup/Checkup.java
- src/main/java/seedu/address/model/person/DateOfBirth.java
Adjust error message for date of birth and checkup times to be more comprehensive
closes #253
> update dates error message

- docs/DeveloperGuide.md
- docs/UserGuide.md
Add return to table of contents for developer guide
Update target audience in User Guide
> update user guide and developer guide
